name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout 
        uses: actions/checkout@v2
      - name: Push imagen registry
        uses: azure/docker-login@v1
        with:
          login-server: registry.digitalocean.com
          username: e0259e347e0942509983dffb61cc619d33d1224a40116f0208e81687d306b9cf
          password: ${{ secrets.REGISTRY_SECRET }}
      - run: |
            docker build . -t registry.digitalocean.com/bmlabs/neva/demo_neva:dev-latest
            docker push registry.digitalocean.com/bmlabs/neva/demo_neva:dev-latest